name: datajoint_sharegroup
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - graphviz
  - ffmpeg
  - openssl
  - ca-certificates
  - pip:
      - -r requirements_datajoint_new.txt
